// Scholarship Database
const scholarships = [
    {
        id: 1,
        name: "National Merit Scholarship",
        amount: "₹50,000",
        deadline: "2026-05-15",
        status: "Open",
        description: "Merit-based scholarship for students with excellent academic performance",
        education: ["12th", "undergraduate"],
        field: ["science", "commerce", "arts", "engineering"],
        percentage: 85,
        income: "0-600000",
        category: ["general", "obc", "sc", "st"],
        group: "class11-12",
        link: "https://scholarships.gov.in",
        documents: [
            "10th and 12th Mark Sheets",
            "Income Certificate",
            "Aadhar Card",
            "Bank Account Details",
            "Passport Size Photograph"
        ]
    },
    {
        id: 2,
        name: "SC/ST Scholarship Program",
        amount: "₹75,000",
        deadline: "2026-06-30",
        status: "Open",
        description: "Financial assistance for SC/ST students pursuing higher education",
        education: ["undergraduate", "postgraduate"],
        field: ["science", "commerce", "arts", "engineering", "medical", "law"],
        percentage: 60,
        income: "0-300000",
        category: ["sc", "st"],
        group: "class11-12",
        link: "https://scholarships.gov.in",
        documents: [
            "Caste Certificate",
            "Income Certificate (below ₹3 Lakhs)",
            "Previous Year Mark Sheets",
            "Admission Proof",
            "Aadhar Card"
        ]
    },
    {
        id: 3,
        name: "Girls Education Scholarship",
        amount: "₹60,000",
        deadline: "2026-04-20",
        status: "Open",
        description: "Encouraging female students to pursue higher education in all fields",
        education: ["12th", "undergraduate", "postgraduate"],
        field: ["science", "commerce", "arts", "engineering", "medical", "law"],
        percentage: 75,
        income: "0-600000",
        category: ["girls"],
        group: "All",
        link: "https://scholarships.gov.in",
        documents: [
            "Academic Transcripts",
            "Income Certificate",
            "Aadhar Card",
            "Gender Certificate",
            "Bank Details"
        ]
    },
    {
        id: 4,
        name: "Engineering Excellence Award",
        amount: "₹1,00,000",
        deadline: "2026-07-15",
        status: "Open",
        description: "Scholarship for exceptional engineering students across all branches",
        education: ["undergraduate"],
        field: ["engineering"],
        percentage: 90,
        income: "0-1000000",
        category: ["general", "obc", "sc", "st"],
        group: "college",
        link: "https://scholarships.gov.in",
        documents: [
            "JEE Score Card",
            "12th Mark Sheet",
            "College Admission Letter",
            "Income Certificate",
            "Project Portfolio (if any)"
        ]
    },
    {
        id: 5,
        name: "Medical Students Support",
        amount: "₹1,50,000",
        deadline: "2026-08-10",
        status: "Open",
        description: "Financial aid for MBBS and BDS students from economically weaker sections",
        education: ["undergraduate"],
        field: ["medical"],
        percentage: 85,
        income: "0-600000",
        category: ["general", "obc", "sc", "st"],
        group: "college",
        link: "https://scholarships.gov.in",
        documents: [
            "NEET Score Card",
            "Income Certificate",
            "Medical College Admission Proof",
            "Aadhar Card",
            "Fee Structure Document"
        ]
    },
    {
        id: 6,
        name: "Post Graduate Research Grant",
        amount: "₹2,00,000",
        deadline: "2026-09-30",
        status: "Soon",
        description: "Research grant for post-graduate students pursuing innovative projects",
        education: ["postgraduate", "doctorate"],
        field: ["science", "engineering", "medical"],
        percentage: 80,
        income: "0-1000000+",
        category: ["general", "obc", "sc", "st"],
        group: "college",
        link: "https://scholarships.gov.in",
        documents: [
            "Research Proposal",
            "Guide Recommendation Letter",
            "Academic Transcripts",
            "Project Synopsis",
            "Publication Record (if any)"
        ]
    },
    {
        id: 7,
        name: "Commerce Students Scholarship",
        amount: "₹40,000",
        deadline: "2026-05-25",
        status: "Open",
        description: "Supporting commerce stream students in their academic journey",
        education: ["12th", "undergraduate"],
        field: ["commerce"],
        percentage: 70,
        income: "0-600000",
        category: ["general", "obc", "sc", "st"],
        group: "all",
        link: "https://scholarships.gov.in",
        documents: [
            "10th and 12th Mark Sheets",
            "Income Certificate",
            "College ID Card",
            "Bank Account Details",
            "Aadhar Card"
        ]
    },
    {
        id: 8,
        name: "OBC Welfare Scholarship",
        amount: "₹50,000",
        deadline: "2026-06-15",
        status: "Open",
        description: "Financial assistance for OBC category students across all streams",
        education: ["undergraduate", "postgraduate"],
        field: ["science", "commerce", "arts", "engineering", "medical", "law"],
        percentage: 65,
        income: "0-300000",
        category: ["obc"],
        group: "all",
        link: "https://scholarships.gov.in",
        documents: [
            "OBC Certificate (Non-Creamy Layer)",
            "Income Certificate",
            "Academic Records",
            "Admission Proof",
            "Aadhar Card"
        ]
    },
    {
        id: 9,
        name: "Arts & Humanities Excellence",
        amount: "₹35,000",
        deadline: "2026-04-30",
        status: "Open",
        description: "Recognizing talent in arts, literature, and humanities",
        education: ["12th", "undergraduate", "postgraduate"],
        field: ["arts"],
        percentage: 75,
        income: "0-600000",
        category: ["general", "obc", "sc", "st"],
        group: "all",
        link: "https://scholarships.gov.in",
        documents: [
            "Portfolio of Work",
            "Academic Transcripts",
            "Income Certificate",
            "Recommendation Letters",
            "Aadhar Card"
        ]
    },
    {
        id: 10,
        name: "Law Students Grant",
        amount: "₹80,000",
        deadline: "2026-07-20",
        status: "Open",
        description: "Supporting aspiring lawyers and legal professionals",
        education: ["undergraduate", "postgraduate"],
        field: ["law"],
        percentage: 80,
        income: "0-1000000",
        category: ["general", "obc", "sc", "st"],
        group: "college",
        link: "https://scholarships.gov.in",
        documents: [
            "Law Entrance Exam Score",
            "Academic Certificates",
            "Income Certificate",
            "College Admission Letter",
            "Internship Records (if any)"
        ]
    },
    {
        id: 11,
        name: "Single Parent Family Support",
        amount: "₹55,000",
        deadline: "2026-05-10",
        status: "Open",
        description: "Special scholarship for students from single-parent households",
        education: ["10th", "12th", "undergraduate"],
        field: ["science", "commerce", "arts", "engineering", "medical", "law"],
        percentage: 60,
        income: "0-300000",
        category: ["general", "obc", "sc", "st", "other"],
        group: "all",
        link: "https://scholarships.gov.in",
        documents: [
            "Single Parent Declaration",
            "Income Certificate",
            "Death/Divorce Certificate (if applicable)",
            "Academic Records",
            "Aadhar Card"
        ]
    },
    {
        id: 12,
        name: "Minority Community Scholarship",
        amount: "₹45,000",
        deadline: "2026-06-05",
        status: "Open",
        description: "Educational support for students from minority communities",
        education: ["undergraduate", "postgraduate"],
        field: ["science", "commerce", "arts", "engineering", "medical", "law"],
        percentage: 65,
        income: "0-600000",
        category: ["other"],
        group: "all",
        link: "https://scholarships.gov.in",
        documents: [
            "Minority Community Certificate",
            "Income Certificate",
            "Academic Transcripts",
            "Admission Proof",
            "Aadhar Card"
        ]
    },
    {
        id: 13,
        name: "Rural Students Advancement",
        amount: "₹50,000",
        deadline: "2026-08-01",
        status: "Soon",
        description: "Empowering students from rural areas to access quality education",
        education: ["12th", "undergraduate"],
        field: ["science", "commerce", "arts", "engineering"],
        percentage: 70,
        income: "0-600000",
        category: ["general", "obc", "sc", "st"],
        group: "all",
        link: "https://scholarships.gov.in",
        documents: [
            "Rural Area Certificate",
            "Income Certificate",
            "Academic Certificates",
            "Domicile Certificate",
            "Aadhar Card"
        ]
    },

    {
        id: 14,
        name: "Differently Abled Students Support",
        amount: "₹70,000",
        deadline: "2026-05-30",
        status: "Open",
        description: "Special assistance for differently-abled students pursuing education",
        education: ["10th", "12th", "undergraduate", "postgraduate"],
        field: ["science", "commerce", "arts", "engineering", "medical", "law"],
        percentage: 50,
        income: "0-600000",
        category: ["general", "obc", "sc", "st", "other"],
        group: "all",
        link: "https://scholarships.gov.in",
        documents: [
            "Disability Certificate (40% or above)",
            "Medical Board Certificate",
            "Academic Records",
            "Income Certificate",
            "Aadhar Card"
        ]
    },
    {
        id: 15,
        name: "State Merit Scholarship",
        amount: "₹30,000",
        deadline: "2026-04-15",
        status: "Open",
        description: "State government scholarship for meritorious students",
        education: ["12th", "undergraduate"],
        field: ["science", "commerce", "arts", "engineering", "medical"],
        percentage: 85,
        income: "0-1000000",
        category: ["general", "obc", "sc", "st"],
        group: "all",
        link: "https://scholarships.gov.in",
        documents: [
            "12th Mark Sheet",
            "Domicile Certificate",
            "Income Certificate",
            "Bank Account Details",
            "College Admission Proof"
        ]
    },
    {
    id: 16,
    name: "Pre-Matric Scholarship for SC Students",
    amount: "₹500/month + ₹500 yearly",
    deadline: "2026-11-01",
    status: "Open",
    description: "For SC students in Class 9–10 with family income below ₹2.5 lakh.",
    education: ["10th"],
    field: ["science", "commerce", "arts"],
    percentage: 50,
    income: "0-250000",
    category: ["sc"],
    group:"school",
    link: "https://scholarships.gov.in",
    documents: [
        "SC Caste Certificate",
        "Income Certificate",
        "Aadhaar Card",
        "Bank Account",
        "Marksheet",
        "School Verification"
    ]
},
{
    id: 17,
    name: "Pre-Matric Scholarship for ST Students",
    amount: "₹500/month + grant",
    deadline: "2026-11-01",
    status: "Open",
    description: "For ST students in Class 9–10 with family income below ₹2.5 lakh.",
    education: ["10th"],
    field: ["science", "commerce", "arts"],
    percentage: 50,
    income: "0-250000",
    category: ["st"],
    group: "school",
    link: "https://scholarships.gov.in",
    documents: [
        "ST Certificate",
        "Income Certificate",
        "Aadhaar Card",
        "Bank Account",
        "Marksheet"
    ]
},

{
    id: 18,
    name: "Begum Hazrat Mahal National Scholarship",
    amount: "₹10,000/year",
    deadline: "2026-10-01",
    status: "Open",
    description: "For minority girls in Class 9–12 with at least 50% marks.",
    education: ["10th", "12th"],
    field: ["science", "commerce", "arts"],
    percentage: 50,
    income: "0-200000",
    category: ["other"],
    group: "school",
    link: "https://scholarships.gov.in",
    documents: [
        "Minority Certificate",
        "Income Certificate",
        "Aadhaar Card",
        "Bank Account",
        "Marksheet"
    ]
},

{
    id: 19,
    name: "Pre-Matric Scholarship for Minority Students",
    amount: "₹600-1000/month",
    deadline: "2026-11-01",
    status: "Open",
    description: "For minority students in Class 9–10 with family income below ₹1 lakh.",
    education: ["10th"],
    field: ["science", "commerce", "arts"],
    percentage: 50,
    income: "0-100000",
    category: ["other"],
    group: "school",
    link: "https://scholarships.gov.in",
    documents: [
        "Minority Certificate",
        "Income Certificate",
        "Aadhaar Card",
        "Bank Account",
        "Marksheet"
    ]
},
{
    id: 21,
    name: "Financial Assistance for Wards of Workers",
    amount: "Fees + allowance",
    deadline: "2026-12-01",
    status: "Open",
    description: "For children of Beedi, Cine and mining workers pursuing Class 11+ education.",
    education: ["12th", "undergraduate", "postgraduate"],
    field: ["science", "commerce", "arts"],
    percentage: 50,
    income: "0-120000",
    category: ["other"],
    group: "class11-12",
    link: "https://scholarships.gov.in",
    documents: ["Income Certificate", "Worker Certificate", "Aadhaar", "Marksheet"]
},

{
    id: 22,
    name: "Merit-cum-Means Scholarship for Minority Students",
    amount: "Up to ₹20,000",
    deadline: "2026-11-10",
    status: "Open",
    description: "For minority students pursuing professional courses.",
    education: ["undergraduate", "postgraduate"],
    field: ["engineering", "medical", "law"],
    percentage: 50,
    income: "0-250000",
    category: ["other"],
    group: "college",
    link: "https://scholarships.gov.in",
    documents: ["Minority Certificate", "Income Certificate", "Admission Proof"]
},

{
    id: 23,
    name: "AICTE Swanath Scholarship",
    amount: "₹50,000/year",
    deadline: "2026-12-01",
    status: "Open",
    description: "For orphan students or those affected by COVID or defense families.",
    education: ["undergraduate"],
    field: ["engineering"],
    percentage: 50,
    income: "0-800000",
    category: ["other"],
    group: "college",
    link: "https://scholarships.gov.in",
    documents: ["Death Certificate", "Income Certificate", "Admission Proof"]
},

{
    id: 24,
    name: "AICTE PG Scholarship (GATE/GPAT)",
    amount: "₹12,400/month",
    deadline: "2026-10-15",
    status: "Open",
    description: "For GATE/GPAT qualified PG students.",
    education: ["postgraduate"],
    field: ["engineering", "medical"],
    percentage: 60,
    income: "0-1000000",
    category: ["general", "obc", "sc", "st"],
    group: "college",
    link: "https://pgscholarship.aicte.gov.in",
    documents: ["GATE Scorecard", "Admission Proof"]
},

{
    id: 25,
    name: "Top Class Education Scholarship for SC Students",
    amount: "Up to ₹2,00,000",
    deadline: "2026-12-01",
    status: "Open",
    description: "For SC students in top institutions like IIT, IIM, AIIMS.",
    education: ["undergraduate", "postgraduate"],
    field: ["engineering", "medical", "law"],
    percentage: 60,
    income: "0-800000",
    category: ["sc"],
    group: "college",
    link: "https://scholarships.gov.in",
    documents: ["SC Certificate", "Income Certificate", "Admission Proof"]
},
{
    id: 26,
    name: "UGC PG Indira Gandhi Scholarship for Single Girl Child",
    amount: "₹36,200/year",
    deadline: "2026-12-01",
    status: "Open",
    description: "For single girl child pursuing postgraduate education.",
    education: ["postgraduate"],
    field: ["science", "commerce", "arts"],
    percentage: 50,
    income: "0-1000000",
    category: ["other"],
    group: "college",
    link: "https://scholarships.gov.in",
    documents: ["Affidavit", "UG Marksheet", "Admission Proof"]
},

{
    id: 27,
    name: "UGC PG Scholarship for University Rank Holders",
    amount: "₹3,100/month",
    deadline: "2026-12-01",
    status: "Open",
    description: "For top rank holders in undergraduate programs.",
    education: ["postgraduate"],
    field: ["science", "commerce", "arts"],
    percentage: 85,
    income: "0-1000000",
    category: ["general", "obc", "sc", "st"],
    group: "college",
    link: "https://scholarships.gov.in",
    documents: ["Rank Certificate", "UG Marksheet"]
},

{
    id: 28,
    name: "UGC PG Scholarship for SC/ST Students",
    amount: "₹7,800/month",
    deadline: "2026-12-01",
    status: "Open",
    description: "For SC/ST students in postgraduate professional courses.",
    education: ["postgraduate"],
    field: ["engineering", "medical", "law"],
    percentage: 50,
    income: "0-1000000",
    category: ["sc", "st"],
    group: "college",
    link: "https://scholarships.gov.in",
    documents: ["SC/ST Certificate", "Admission Proof"]
},

{
    id: 29,
    name: "PM Scholarship Scheme for CAPF",
    amount: "₹30,000–36,000/year",
    deadline: "2026-11-01",
    status: "Open",
    description: "For wards of CAPF and Assam Rifles personnel.",
    education: ["undergraduate"],
    field: ["engineering", "medical", "law"],
    percentage: 60,
    income: "0-1000000",
    category: ["other"],
    group: "college",
    link: "https://scholarships.gov.in",
    documents: ["Service Certificate", "Marksheet"]
},

{
    id: 30,
    name: "Dr. Ambedkar Post-Matric Scholarship (Gujarat)",
    amount: "Fees + allowance",
    deadline: "2026-11-15",
    status: "Open",
    description: "For EBC students in Gujarat pursuing higher education.",
    education: ["12th", "undergraduate", "postgraduate"],
    field: ["science", "commerce", "arts"],
    percentage: 50,
    income: "0-100000",
    category: ["general"],
    group: "state",
    link: "https://scholarships.gov.in",
    documents: ["Income Certificate", "Admission Proof"]
},

{
    id: 31,
    name: "Tata Capital Pankh Scholarship",
    amount: "Up to ₹20,000",
    deadline: "2026-09-01",
    status: "Open",
    description: "For economically weaker students in Class 11 and UG.",
    education: ["12th", "undergraduate"],
    field: ["science", "commerce", "arts"],
    percentage: 60,
    income: "0-400000",
    category: ["other"],
    group: "private",
    link: "https://buddy4study.com",
    documents: ["Income Certificate", "Marksheet"]
},

{
    id: 32,
    name: "Sitaram Jindal Foundation Scholarship",
    amount: "₹500–₹2,000/month",
    deadline: "2026-09-01",
    status: "Open",
    description: "For students from Class 11 to UG level from low-income families.",
    education: ["12th", "undergraduate"],
    field: ["science", "commerce", "arts"],
    percentage: 60,
    income: "0-250000",
    category: ["general", "obc", "sc", "st"],
    group: "private",
    link: "https://www.sitaramjindalfoundation.org",
    documents: ["Income Certificate", "Marksheet"]
},

{
    id: 33,
    name: "Swami Vivekananda Merit Scholarship",
    amount: "₹1,000–₹8,000/month",
    deadline: "2026-10-01",
    status: "Open",
    description: "For West Bengal students with high academic performance.",
    education: ["12th", "undergraduate"],
    field: ["science", "commerce", "arts"],
    percentage: 75,
    income: "0-250000",
    category: ["other"],
    group: "state",
    link: "https://svmcm.wbhed.gov.in",
    documents: ["Domicile Certificate", "Marksheet"]
},

{
    id: 34,
    name: "SBI Asha Scholarship",
    amount: "₹15,000/year",
    deadline: "2026-10-15",
    status: "Open",
    description: "For school students with strong academic performance.",
    education: ["10th", "12th"],
    field: ["science", "commerce", "arts"],
    percentage: 75,
    income: "0-300000",
    category: ["general", "obc", "sc", "st"],
    group: "school",
    link: "https://sbiashascholarship.co.in",
    documents: ["Marksheet", "Income Certificate"]
},

{
    id: 35,
    name: "Vidyadhan Scholarship",
    amount: "₹10,000/year",
    deadline: "2026-07-01",
    status: "Open",
    description: "For Class 10 passed students entering Class 11.",
    education: ["12th"],
    field: ["science", "commerce", "arts"],
    percentage: 85,
    income: "0-200000",
    category: ["general", "obc", "sc", "st"],
    group: "class11-12",
    link: "https://www.vidyadhan.org",
    documents: ["10th Marksheet", "Income Certificate"]
},
{
    id: 36,
    name: "LIC Golden Jubilee Scholarship (Girl Child)",
    amount: "₹15,000/year",
    deadline: "2026-10-01",
    status: "Open",
    description: "Scholarship by LIC Foundation for girl students in Class 11–12 or diploma courses.",
    education: ["12th"],
    field: ["science", "commerce", "arts"],
    percentage: 60,
    income: "0-450000",
    category: ["other"],
    group: "private",
    link: "https://www.licindia.in",
    documents: ["10th Marksheet", "Income Certificate"]
},

{
    id: 37,
    name: "Clinic Plus Scholarship for Girls",
    amount: "₹20,000/year",
    deadline: "2026-06-01",
    status: "Open",
    description: "Scholarship for girls based on academics and extracurriculars (primarily available in Karnataka).",
    education: ["10th", "12th"],
    field: ["science", "commerce", "arts"],
    percentage: 60,
    income: "0-1000000",
    category: ["other"],
    group: "school",
    link: "https://www.clinicplus.in",
    documents: ["Marksheet", "Essay", "Certificates"]
},

{
    id: 38,
    name: "Muskaan Scholarship Program",
    amount: "Up to ₹12,000",
    deadline: "2026-09-01",
    status: "Open",
    description: "For children of drivers and mechanics from EWS background.",
    education: ["10th", "12th"],
    field: ["science", "commerce", "arts"],
    percentage: 60,
    income: "0-800000",
    category: ["other"],
    group: "school",
    link: "https://buddy4study.com",
    documents: ["Income Certificate", "Occupation Proof"]
},

{
    id: 39,
    name: "Vahani Scholarship",
    amount: "Full UG Funding",
    deadline: "2026-11-01",
    status: "Open",
    description: "Apply in Class 12; provides full funding for undergraduate (UG) studies including tuition and living.",
    education: ["12th"],
    field: ["science", "commerce", "arts"],
    percentage: 85,
    income: "0-300000",
    category: ["general", "obc", "sc", "st"],
    group: "class11-12",
    link: "https://www.vahanischolarship.com",
    documents: ["10th & 11th Marksheet", "Income Certificate"]
},

{
    id: 40,
    name: "Mahindra Saarthi Scholarship",
    amount: "₹10,000",
    deadline: "2026-02-01",
    status: "Open",
    description: "For daughters of truck drivers pursuing higher education.",
    education: ["12th", "undergraduate"],
    field: ["science", "commerce", "arts"],
    percentage: 50,
    income: "0-1000000",
    category: ["other"],
    group: "private",
    link: "https://buddy4study.com",
    documents: ["Driving License", "Marksheet"]
},

{
    id: 41,
    name: "HDFC Parivartan ECSS Scholarship",
    amount: "₹15,000/year",
    deadline: "2026-10-01",
    status: "Open",
   description: "For students facing financial crisis such as loss of earning member, illness, or disaster.",
    education: ["10th", "12th"],
    field: ["science", "commerce", "arts"],
    percentage: 55,
    income: "0-250000",
    category: ["general", "obc", "sc", "st"],
    group: "school",
    link: "https://buddy4study.com",
    documents: ["Income Certificate", "Crisis Proof"]
},

{
    id: 42,
    name: "Sitaram Jindal School Scholarship",
    amount: "₹500–₹1,000/month",
    deadline: "2026-09-01",
    status: "Open",
    description: "For Class 11–12 students from low-income families.",
    education: ["12th"],
    field: ["science", "commerce", "arts"],
    percentage: 60,
    income: "0-200000",
    category: ["general", "obc", "sc", "st"],
    group: "class11-12",
    link: "https://www.sitaramjindalfoundation.org",
    documents: ["Marksheet", "Income Certificate"]
}
];
